import { Inter } from "next/font/google";
import "@styles/globals.css";
import Nav from "@components/Nav";
import Provider from "@components/Provider";
import Container from "@components/Container";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className=" ">
        <div className="main -z-50">
          <div className="gradient"></div>
        </div>

        <Provider>
          <Nav />

          <Container className="px-4 sm:px-0 lg:max-w-5xl">
            <main className="">{children}</main>
          </Container>
        </Provider>
      </body>
    </html>
  );
}
